version: "3.8"

services:
  minecraft:
    build: .
    container_name: minecraft_server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/minecraft
    environment:
      - EULA=true
      - MEMORY=4G
    restart: unless-stopped
